Updates

diff --git a/Fluxes b/Fluxes
--- a/Fluxes
+++ b/Fluxes
@@ -11,6 +11,7 @@
 name=$0
 dir=$1 # directories where data is stored
 [ -z "$dir" ] && echo "Error: Please enter location of NetCDFs for globbing/testing." && exit 1
+! [ -d "$dir" ] && echo "Error: Directory \"$dir\" not found." && exit 1
 output=$dir/fluxes_${HOSTNAME%%.*}.log # store here
 header="| nlat | size (version) | name | real (s) | user (s) | sys (s) |\n| --- | --- | --- | --- | --- | --- |\n"
 rm $output 2>/dev/null
@@ -53,32 +54,32 @@ for data in ${datas[@]}; do
   printf "\n$header" >>$output # add header for each new file
 
   # Julia
-  bench "Julia + PackageCompiler" ./jl/${name} $data
+  bench "Julia + PackageCompiler" ./jl_${HOSTNAME%%.*}/${name} $data
   # bench "Julia (naive)" julia -e 'push!(LOAD_PATH, "./"); using fluxes; fluxes.eddy_flux("'${name}'")' # will be ridiculously slow, don't bother
 
   # Skip to big files
   # let counter+=1
   # [ $counter -le 10 ] && continue
   # Python with xarray method
-  bench "XArray + no dask" python ${name}.py $data 0 0
+  bench "XArray + no dask" python ${name}.py $data 0
 
   # Python with xarray and Dask chunking by 2D slice
-  # bench "XArray + 100-timestep chunks" python ${name}.py $data 100 60
+  # bench "XArray + 100-timestep chunks" python ${name}.py $data 100
   if [ $dir == 1lev ]; then
-    bench "XArray + 1000 t chunks" python ${name}.py $data 1000 1
-    # bench "XArray + 200 t chunks"  python ${name}.py $data 200 1
-    bench "XArray + 100 t chunks"  python ${name}.py $data 100 1
-    # bench "XArray + 50 t chunks"   python ${name}.py $data 50 1
-    # bench "XArray + 20 t chunks"   python ${name}.py $data 20 1
-    bench "XArray + 10 t chunks"   python ${name}.py $data 20 1
+    bench "XArray + 1000 t chunks" python ${name}.py $data 1000
+    # bench "XArray + 200 t chunks"  python ${name}.py $data 200
+    bench "XArray + 100 t chunks" python ${name}.py $data 100
+    # bench "XArray + 50 t chunks"   python ${name}.py $data 50
+    # bench "XArray + 20 t chunks"   python ${name}.py $data 20
+    bench "XArray + 10 t chunks" python ${name}.py $data 20
   elif [ $dir == 60lev ]; then
-    bench "XArray + 200 t chunks" python ${name}.py $data 200 60
-    # bench "XArray + 50 t chunks"  python ${name}.py $data 50 60
-    bench "XArray + 20 t chunks"  python ${name}.py $data 20 60
-    # bench "XArray + 10 t chunks"  python ${name}.py $data 10 60
-    # bench "XArray + 5 t chunks"   python ${name}.py $data 5 60
-    bench "XArray + 2 t chunks"   python ${name}.py $data 2 60
-    # bench "XArray + 1 t chunks"   python ${name}.py $data 1 60
+    bench "XArray + 200 t chunks" python ${name}.py $data 200
+    # bench "XArray + 50 t chunks"  python ${name}.py $data 50
+    bench "XArray + 20 t chunks" python ${name}.py $data 20
+    # bench "XArray + 10 t chunks"  python ${name}.py $data 10
+    # bench "XArray + 5 t chunks"   python ${name}.py $data 5
+    bench "XArray + 2 t chunks" python ${name}.py $data 2
+    # bench "XArray + 1 t chunks"   python ${name}.py $data 1
   else
     echo "Error: Unknown chunk combos for sample data in dir \"$dir\"."
     exit 1
@@ -87,7 +88,6 @@ for data in ${datas[@]}; do
   # CDO method
   # NOTE: On mac just run with serial IO
   # NOTE: Serial IO turned out to be really small difference
-  export DYLD_LIBRARY_PATH=""
   bench "CDO" ${name}.cdo $data
   # bench "CDO no expr" ${name}_stupid.cdo $data
   # bench "CDO + serial IO" ${name}_stupid.cdo $data '-L'
@@ -98,6 +98,7 @@ for data in ${datas[@]}; do
   export DYLD_LIBRARY_PATH="/usr/local/lib/gcc/4.9"
   bench "NCL" ncl -Q -n "filename=\"$data\"" "large=\"0\"" ${name}.ncl
   # bench "NCL + LargeFile" ncl -Q -n "filename=\"$data\"" "large=\"1\"" ${name}.ncl
+  export DYLD_LIBRARY_PATH=""
 
   # NCO method with NCAP
   # Add options for handling large files; see: http://nco.sourceforge.net/nco.html#Temporary-Output-Files
